version: '3.8'

services:
  vocabulary-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: vocabulary-learning-app
    restart: unless-stopped
    
    ports:
      - "30001:80"
    
    environment:
      - NODE_ENV=production
      - REACT_APP_VERSION=1.0.0
    
    networks:
      - vocabulary_network
    
    # Health check (ora integrato nel Dockerfile)
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Limiti risorse per TrueNAS Scale
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    
    labels:
      # Labels per TrueNAS Scale management
      - "com.truenas.app=vocabulary-learning"
      - "com.truenas.app.version=1.0.0"
      - "com.truenas.app.description=Vocabulary Learning App con AI Assistant"
      - "traefik.enable=true"
      - "traefik.http.routers.vocabulary.rule=Host(`vocabulary.local`)"
      - "traefik.http.services.vocabulary.loadbalancer.server.port=80"

# ==========================================
# Versione alternativa per development
# ==========================================
  vocabulary-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: vocabulary-learning-app-dev
    restart: unless-stopped
    profiles: ["dev"]
    
    command: npm start
    
    ports:
      - "30002:3000"
    
    volumes:
      - .:/app
      - /app/node_modules
      - npm_cache:/root/.npm
    
    environment:
      - NODE_ENV=development
      - REACT_APP_VERSION=1.0.0-dev
      - CHOKIDAR_USEPOLLING=true
    
    networks:
      - vocabulary_network

# Network isolato
networks:
  vocabulary_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Persistent volumes
volumes:
  npm_cache:
    driver: local